### ISSUE TITLE
sqlite reader fails

### ISSUE THREAD

**Issue by setop** [eatonphil/dbcore#10]
I fixed it by replacing

https://github.com/eatonphil/dbcore/blob/38cb36d58cde21549c72b67e62dd17bccf813b40/src/Reader/SQLite.fs#L36

by 

`(SELECT count(1) FROM sqlite_master WHERE tbl_name="entry" AND sql LIKE '%%AUTOINCREMENT%%'),`

**Comment by eatonphil** [comment]
You'll have to give more detail but the SQLite reader is part of automated testing currently so it is definitely supported.

**Comment by setop** [comment]
Your test probably makes the assumption that primary key is always "AUTOINCREMENT" which is not always the case.

I reproduced it using your "todo" example. If I remove "AUTOINCREMENT" for table "notes" then `dbcode` fails.
