### ISSUE TITLE
DBCORE_API_PREFIX not set

### ISSUE THREAD

**Issue by setop** [eatonphil/dbcore#11]
https://github.com/eatonphil/dbcore/blob/38cb36d58cde21549c72b67e62dd17bccf813b40/templates/browser/react/src/api/request.ts#L2

I worked around it by hard coding the value

**Comment by eatonphil** [comment]
Did you set `address` in `api.yml`? See how `api.yml` is set up in examples/todo.

**Comment by eatonphil** [comment]
I can confirm this works if you configure `api.yml` in your project root directory.
