### ISSUE TITLE
What are `&ownedOrOrgAdmin` or `*ownedOrOrgAdmin`?

### ISSUE THREAD

**Issue by syabro** [eatonphil/dbcore#16]
Documentation has these terms, but I can't find any reference about them in the repo

**Comment by eatonphil** [comment]
Those are pointers defined/used solely in yaml. See http://blogs.perl.org/users/tinita/2019/05/reusing-data-with-yaml-anchors-aliases-and-merge-keys.html for some more detail.

Basically & creates something you can reference later on in yaml with *.
